### ISSUE TITLE
Is there no example on how to actually implement the waypoint transversal on an object?

### ISSUE THREAD

**Issue by MostHated** [dubit/duck#91]
Hello all,
    I have been trying to follow suit with how the tests were setup so I could make a script to put on the gameobject I wish to move, but I am just not quite figuring it out because of the fact there are multiple waypoints of type WaypointPath once you do GetPath. Is there an example of how to go about using that after you get the return value of the actual path? I tried to look on github if anyone else was using this same system so I could see how they did it, but I was unable to find anything.

Thanks
-MH

**Comment by MostHated** [comment]
I tried to take some bits and pieces from the tests and mix them with another waypoint thing I found, but I don't think I am going about it properly. 

https://hastebin.com/segepafeza.cs

Is there any sort of official demonstration of usage perhaps I could take a look at?

Thanks!
-MH

**Comment by MostHated** [comment]
After a quite a lot more trial and error I was able to get things working, still though, if there was an official implementation I would love to see it!

**Comment by pmead** [comment]
@MostHated awesome that you got them to work, but unfortunately there isn't any official documentation for waypoints available yet.

We're in the midst of splitting this repository up so that its easier to maintain and add relevant documentation for each part - waypoints updates and documentation will eventually be in [this repo](https://github.com/dubit/unity-waypoints).

Closing and moving here: [unity-waypoints issue #3]( https://github.com/dubit/unity-waypoints/issues/3)
